// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    ATable: typeof import('@arco-design/web-vue')['Table']
    VmsList: typeof import('./src/components/vms/list.vue')['default']
  }
}

export { }
