import api from '~/utils/ajax'

export default api
export const getIndex = () => api.get('/Index/indexData')
export const login = data => api.post('/Login/index', data)
export const reg = data => api.post('/Login/tuiguangma_regsempost', data)
export const regsems = data => api.get('/Login/regsem', data)
export const buyGood = id => api.get('/Robot/buy', { id })
export const send_edit_code = phone => api.get(`/Sem/send_edit_code/mobile/${phone}`)
export const strikeRobot = id => api.get('/Robot/jiesuan', { id })
export const realName = () => api.get('/Robot/docertification')
export const iscertification = () => api.get('/Robot/iscertification')
export const yijianlingquBtn = () => api.post('/Robot/yijianlingqu_btn')
export const docertification = data => api.post('/Robot/docertification', data)
export const getRobot = () => api.get('/Robot/robot')
export const getUserInfo = () => api.get('/Wallet/index')
export const getHuiyuan = () => api.get('/Wallet/huiyuan')
export const tgm = () => api.get('/Wallet/tgm')
export const getQiandao = data => api.get('/Wallet/qiandao', data)
export const qiandao = data => api.post('/Wallet/qiandao', data)
export const getChongZhi = () => api.get('/Wallet/chongzhi')
export const getTuandui = data => api.get('/Wallet/tuandui', data)
export const getTixian = () => api.get('/Wallet/tixian')
export const getZhifu = () => api.get('/Wallet/zhifu')
export const withpost = data => api.post('/Wallet/withpost', data)
export const zhifupost = data => api.post('/Wallet/zhifupost', data)
export const getJiaoYiLog = data => api.get('/Wallet/jiaoyi_log', data)
export const getChongZhiLog = data => api.get('/Wallet/chongzhi_log', data)
export const getTiXianLog = data => api.get('/Wallet/tixian_log', data)
export const getDetail = id => api.get('/article/detail', { id })
export const pay_add_order = data => api.post('/Payment/pay_add_order', data)
export const pay_erweima = data => api.post('/wallet/pay_erweima', data)
export const pay = data => api.post('/Payment/pay', data)
